### ISSUE TITLE
Comparison with rocket:module

### ISSUE THREAD

**Issue by dandv** [vazco/universe-modules#14]
Since I just gave a [talk on prior art](http://www.youtube.com/watch?v=aa3C9FilfPg&t=2h32m20s) at the July DevShop featuring @benajmn's [ES2015 talk](https://www.youtube.com/watch?v=aa3C9FilfPg#t=2755), I thought I'd ask how this package is different from @trusktr's [rocket:module](https://github.com/meteor-rocket/module), after seeing both mentioned in [this forum thread](https://forums.meteor.com/t/universe-modules-use-es6-es2015-modules-in-meteor-today/6764).

**Comment by trusktr** [comment]
@dandv I was going to present a preview of `rocket:module` after you, at DevShop, but Sam (I think that was her name) didn't know I was there, so when it was my turn I got skipped. :laughing: hehe

Here's a [quick comparison](https://github.com/meteor/meteor/issues/4310#issuecomment-126945180).

**Comment by trusktr** [comment]
It was funny how fast you talked. hehe. And then kept going after the timer ended. EPIC. :laughing: :laughing: :laughing:

**Comment by dandv** [comment]
Yeah, I was wondering where you'd disappeared! You should book a slot as soon as http://lightning-talks.meteor.com/ reopens.

**Comment by MacRusher** [comment]
Hi @dandv thanks for great question.

`universe:modules` and `rocket:module` are both introducing modules to Meteor, but have completely different ways to achieve this goal.

We're based on MDG Babel implementation and use SystemJS/ES6LoaderPolyfill to be as ES2015 spec compliant as possible. We're trying to be future ready and maybe switch to MDG modules implementation when it's ready.

On the other hand, `rocket:modules` are based on Webpack.
Webpack have lots of advantages, but I don't see MDG dropping Isobuild in favor of it anytime soon.

So the question and real comparison should be between ES2015 modules and Webpack, which is in some kind like comparing apples to oranges.

Another thing worth notice is that universe:modules is part of [Universe](http://unicms.io) - we will be releasing soon some packages that will allow you to build easily a CMS on top of Meteor and React.

Edit: I replied also in the original thread: https://github.com/meteor/meteor/issues/4310
