### ISSUE TITLE
CJSX

### ISSUE THREAD

**Issue by zachdixon** [vazco/universe-modules#16]
Love this package, but just curious if there are any plans for support CJSX (`*.import.cjsx`) files if that's possible?

Will probably make the switch to ES6/JSX though since it'll be worth it for modules.

**Comment by MacRusher** [comment]
Hi. We don't use CJSX in our company, and unfortunately we don't have plans to support it in the near future. But we can add it if there will be a demand for such feature and it could be integrated into Babel build process.

We're open for pull requests if you have some ideas on how this could be implemented.
