### ISSUE TITLE
is this package just for modules?

### ISSUE THREAD

**Issue by dcsan** [vazco/universe-modules#21]
or should other es6 syntax be enabled in your demo app?
I was not able to get any other basic stuff to run:

https://forums.meteor.com/t/universe-modules-use-es6-es2015-modules-in-meteor-today/6764/29?u=dcsan

thanks

**Comment by MacRusher** [comment]
This package add modules on top of Meteor `ecmascript` package so everything else should also work. But you need to use `.import.js` extension, not just `.js` (Sanjo already explained this in the forums)
