### ISSUE TITLE
Use for Meteor 1.2rc

### ISSUE THREAD

**Issue by rolfnl** [vazco/universe-modules#22]
Do you think you need release an updated/lightweight version of this package now that 1.2rc is out? At the moment 1.2 doesn't support import/export of modules but do support ES2015 via ecmascript/babel. So should there be a lighter version of universe-modules using the built in packages. And will there be conflicts now using both 1.2rc and universe-modules? I didn't have time to test yet...

**Comment by MacRusher** [comment]
> So should there be a lighter version of universe-modules using the built in packages.

universe:modules is already using these packages :) `ecmascript` uses MDG babel compiler under the hood, so do we. These packages exists for some time, they are just officially released as a default in 1.2.

> And will there be conflicts now using both 1.2rc and universe-modules?

There shouldn't be any conflicts as we use separate file extensions `*.import.js(x)` and not just `*.js`.
Our modules should work with 1.2 out of the box without any changes (but I haven't tested it yet).

But new build plugin system introduced in 1.2 looks promising and will allow us to make better integration. We will release version 0.5 that will make use of it and require Meteor 1.2 to work.

**Comment by SeriousM** [comment]
> The ES2015 module syntax (import/export) is not supported yet in Meteor 1.2.

https://quip.com/RXFlAk9Rc2xI

**Comment by MacRusher** [comment]
ES2015 modules was never planned for Meteor 1.2 :) This is why our package is so cool :sunglasses: 

I already started work on new version of universe:modules that will make use of new 1.2 features, but right now this task is postponed so I cannot give you any estimate on it.

From my tests, current version of universe:modules should work on Meteor 1.2 as is.

**Comment by MacRusher** [comment]
I've just released version 0.5.0 that make use of new Meteor 1.2 features

**Comment by SeriousM** [comment]
woohoo, cool! I'll go and check that out!

**Comment by MacRusher** [comment]
Check upgrade notes in readme and changelog.md because there are few breaking changes in this release! :)
