### ISSUE TITLE
Alternative File Extensions

### ISSUE THREAD

**Issue by AdamBrodzinski** [vazco/universe-modules#3]
Have you considered adding the `.es6.js` extension so that people currently using babel can switch over without changing all of their file extensions? I suppose this would have to be opt in with a config to not break existing babel projects. Just a thought!

**Comment by MacRusher** [comment]
I can do it, but you're sure that this is a good idea?

All `.es6.js` file are loaded automatically by Meteor and `.import.js` files need to be loaded explicit.  
Changing name isn't enough to make this work.

IMHO it is better to do it manually and this way mark files that are ready for loading as a module, and actually are exporting something.

Once files are module-ready you can always use `rename` command or write simple bash script to rename all file.

Does this answer satisfy you?

**Comment by AdamBrodzinski** [comment]
Ah good point. I guess my initial reaction was that the filename becomes really long in my file tree. I think having them be explicitly loaded for now is prob. best.

**Comment by MacRusher** [comment]
Yeah names can get quite long sometimes, but this is just lesser evil.

We experimented with `.mod.js`, `.i.jsx` etc. but in the end readability is more important so we stick to `.import.js`.

Closing for now.

PS. How react-meteor-tutorial.com is going? I can't wait your screencasts :)
