### ISSUE TITLE
Please bring back support for importing '*.import'

### ISSUE THREAD

**Issue by Gaelan** [vazco/universe-modules#30]
…or let us use plain `.js` files. We shouldn't be stuck on `0.4` if we need TypeScript support.

**Comment by MacRusher** [comment]
Sorry for that, I've removed this while refactoring the code but I'll bring it back.
You can expect new version later today.

I'm also working on a package that will allow to use plain .js extension.

**Comment by MacRusher** [comment]
I've just published version 0.5.1, please let me know if it works for you.

**Comment by MacRusher** [comment]
Closing, please reopen if you still have any issues.
