### ISSUE TITLE
Question : Using System.import  for usage in Meteor App.  

### ISSUE THREAD

**Issue by romans127** [vazco/universe-modules#34]
Hello , 

When using System.import are we supposed to put the entire code in System.import block or define system.import then outside of the block write our code.  So for example the basic starter app has if meteor is client , if meteor is server and the logic in between for the basic counter template helpers. 

Should all that code be moved inside system import or should system.import be defined above this logic ?

**Comment by MacRusher** [comment]
Sorry I'm not sure what you're asking about.

`System.import` return a promise that will be resolved once all required modules will be loaded and executed. You can threat it as any other promise, and use it wherever you want.

Of course you can have code outside of this promise, but in this case you got no guarantee about execution order.

If you could give me an example you talking about I can be more specific about this.
