### ISSUE TITLE
Is it possible to access modules from `meteor shell` or from the browser console?

### ISSUE THREAD

**Issue by mtchllbrrn** [vazco/universe-modules#37]
See topic.

**Comment by MacRusher** [comment]
I haven't tried that, but you should be able to load them using dynamic syntax like in normal .js files: `System.import('/absolute/path/to/module').then(module => console.log(module))`.
The `import * from` syntax must be parsed by babel so it won't work in already running environment.

**Comment by mtchllbrrn** [comment]
I'm not able to get this to work. How would I go about doing something as simple as interacting with my `meteor-accounts` `Users` collection in the shell?  I've tried executing this code in the shell and on the server at runtime:

```
System.import('/collections/users').then(function(Users) {
  console.log(Users);
});
```

Meteor shell returns `{ _37: 0, _12: null, _59: [] }`.

Executing at run-time on the server doesn't log anything.

**Comment by cristo-rabani** [comment]
Check it: System.import('/collections/users').then(function(module) {
  console.log(module.Users, module['default']);
});

**Comment by mtchllbrrn** [comment]
Ah, I see now. That is a bit cumbersome, though, and seems to indicate that ES6 modules are best relegated to particular parts of the app. React components, for instance. I'm still trying to figure out where ES6 modules can fit into my Meteor workflow, any thoughts on best practices?
