### ISSUE TITLE
modules on linux (centos 7)

### ISSUE THREAD

**Issue by ghost** [vazco/universe-modules#39]
Hello. After spending day in failed tries to make modules working on my laptop with Centos 7 want to place here my findings.

First I tried to use universe:modules, following simpliest app example of two components, final component and file.js. It appears that System.import end up in build error (unrecognized token <), if it is placed anywhere but in if(Meteor.isServer). Inside if(Meteor.isServer) build finished successfully, but strange things start to happen. If try to open app in browser then in console can see that module load failed. If try to use console.log to determine which part of code is actually not working on server it appears that System.import promise not return anything. .catch(err)  though always fired, but err appeared to be empty object (with 0 enumerable properties). 

Name of module appear to be not important at all, even if write there random string behaviour is just the same. If trying to place import reserved word as first line of code always get build error of unexpected reserved word. 

Then I tried to use universe:modules-entrypoint. This one always end up in failure in build time: https://github.com/vazco/meteor-universe-modules-entrypoint/issues/2

Want to add that I tried to look into rocket:module, found it can import module, but couldn't find way to export it, and also tried to use meteor 1.3-modules-beta 0 1 and 2, all end up in same issue as with universe:modules-entrypoint, but saying that there is no property module on object.

On windows though 1.3 modules beta worked at once. This is really frustrating end up without modules on linux, so please look into this matter.

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
