### ISSUE TITLE
Doesn't work with import.js

### ISSUE THREAD

**Issue by vjau** [vazco/universe-modules#4]
When i write a file with import.js extension, the builder complain about "unexpected reserved word" on line with import/export statements. It seems those files are builded with the regular Meteor build tool and NOT by universe-modules.
When i rename those files to .import.jsx instead of .import.js it works.

Thank you.

**Comment by MacRusher** [comment]
It's working for me.

I've set up new branch for this issue on demo app:
https://github.com/vazco/demo_modules/tree/issue-4

@vjau could you check it out and tell me if it works for you?
It should print `isOK` in the console.
There is one new file `components/test.import.js` and some changes in `main.js`

**Comment by vjau** [comment]
I cannot get it to reproduce, sorry.
