### ISSUE TITLE
Meteor 1.3 compatibility

### ISSUE THREAD

**Issue by timothyarmes** [vazco/universe-modules#40]
Hi,

With Meteor 1.3 around the corner (which has built-in support for modules) I'm reticent to use any of your packages. Will you be updating your components to use the built-in modules system?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
