### ISSUE TITLE
Problem with Arrow Function?

### ISSUE THREAD

**Issue by rikkuporta** [vazco/universe-modules#41]
Hi, 
i'm using React ES6 classes and Meteor for an application and I wanted to use arrow function instead of bind(this) but it seems not to work. Is this just a missing compiler feature, a bug or an error on my side?
![image](https://cloud.githubusercontent.com/assets/3002584/13123122/f7168c8e-d5ba-11e5-9504-fa486bc8f4ad.png)
Defining static Properties is also not possible, but this error comes not from universe:modules but from jsx (and universe:ecmascript)

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
