### ISSUE TITLE
Use universe:modules in package

### ISSUE THREAD

**Issue by lukejagodzinski** [vazco/universe-modules#42]
Hi, is it possible to use this in a package? I would like to provide backward compatibility for Meteor 1.2 in a package written for Meteor 1.3 and using ES modules. I think about including some conditionals that would use the `universe:modules` package if it detects that the current Meteor version is < 1.3. I was playing around with `universe:ecmascript` to make use of it in a package but it isn't working and I can't find any example in a documentation. So is it possible?

**Comment by MacRusher** [comment]
Hi,
First problem that I see is that our import syntax isn't 100% the same as Meteor is using in 1.3. 
But we could achieve that with tweaks to our custom loader.
Imports from npm is something that we might not be able to emulate.

Other problem is file naming, but here `universe:ecmascript` could come in handy. It should work in a package, we're using it internally this way. What errors exactly do you have?

I can help you make this work, you're talking about 2.0 version of Astronomy right?

**Comment by lukejagodzinski** [comment]
It's funny, after I've posted this issue I've watched a Meteor conference in London and it appeared that you're also from Poland :) but I will continue writing in English as it may also help others with similar problem :).

Lack of NPM support right now is not a problem as I'm using Atmosphere wrappers of NPM packages. And yes I think that `universe:ecmascript` could solve all the problems with file naming as it loads all files. I just need an easy way of "ignoring" modules syntax that would load all the files at once if can't be done other way :).

It was complaining about usage of the `import` word, that it should be used at the top of the file.

Yes I'm working on Astronomy 2.0 :). Help would be appreciated :). Right now I won't be available for next 2 weeks but after that I will write to you.

Thanks! :)

**Comment by MacRusher** [comment]
> It was complaining about usage of the import word, that it should be used at the top of the file.

Sounds like a problem with Babel, but I haven't stumble upon this one yet.

Ping me when you're back and point me into code thats not working and I'll try to help with it.

If you're gonna be in Wroclaw anytime soon we can also go grab a beer if you want :)

**Comment by lukejagodzinski** [comment]
Ok I will.

Yes sure, why not :). I will probably visit Wroclaw this year :) not sure when exactly but will let you know :)

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
